services:
    grafana:
      image: grafana/grafana:12.1.0
      restart: unless-stopped
      environment:
        - GF_AUTH_DISABLE_LOGIN_FORM=false
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
        - GF_USERS_ALLOW_SIGN_UP=false
      ports:
        - "3001:3000"
